import React from 'react';
import '../../App.css';
import CardItem from '../CardItem';
import { Link } from 'react-router-dom';
import Footer from '../Footer'


export default function Bird() {
  // return <h1 className='sign-up'>LIKE & SUBSCRIBE</h1>;
  return (
    <>
    <div className='cards'>
      <h1>Confira nossos Produtos </h1>
      <div className='cards__container'>
        <div className='cards__wrapper'>
          <ul className='cards__items'>
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
          </ul>
          <ul className='cards__items'>
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
          </ul>
          <ul className='cards__items'>
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
          </ul>
          <ul className='cards__items'>
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
            <CardItem
              src='images/birdimg.jpg'
              text='Rações'
              path='/products'
            />
          </ul>
        </div>
      </div>
    </div>

<Footer/>
   
    </>
  );
}
